### if set to true will open the detail view of the vocab card
auto_open = true

### the following config options will need you to be logged in
### get the sid cookie from your browser and paste it here, then uncomment the option
# session_id = "paste your sid value here"

### set this option to the id of the deck where you want vocab cards added automatically
### you can get the id by clicking on the detail view of a deck and looking at your browser url bar
### if this option is not set, it will not add cards automatically
# auto_add = 0

### uncomment this option to automatically add cards added via jpdb-connect to
### the front of your review queue (FORQ)
### it will work even if the card is locked
### it won't work if the card is suspendend or not in any deck (but auto_add helps here)
# auto_forq = true

### works like auto_forq except that it unlocks the card
# auto_unlock = true


### automatically marks card as forgotten
### this inserts a failed review for the card
### and removes it from all decks which are marked as known
# auto_forget = true

### for debugging and development purposes
# log_level = "Trace"