### if set to true will open the detail view of the vocab card
auto_open = true

### the following config options will need you to be logged in
### get the sid cookie from your browser and paste it here, then uncomment the option
# session_id = "paste your sid value here"

### set this option to the id of the deck where you want vocab cards added automatically
### you can get the id by clicking on the detail view of a deck and looking at your browser url bar
### if this option is not set, it will not add cards automatically
# auto_add = 0
